
name: "Data Import Task"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  import:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
          chmod +x script/install.sh
          script/install.sh

      # Add or replace dependency steps here
      #- name: Install Ruby and gems
      #  uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
      #  with:
      #    bundler-cache: true

      - name: Setup
        run: |
          env
          gem install bundler aws_lambda_ric
          bundle install -j4

      - name: Run Task
        run: |
          rails import:run

      - name: Check Task And Submit Issue
        run: |
          env
          err=$(cat log/${RAILS_ENV}.log | jq .incident.reason)
          echo $err
          if [ "$err" != "null" ]; then
            echo "NG"
            rails issue:run
            exit 1
          fi


